name: streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.0.4=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - pip:
    - https://github.com/irwin-amago/ellips2ortho-aus/blob/main/rasterio-1.2.10-cp38-cp38-win_amd64.whl
